@startuml
left to right direction

actor "Team Member" as TeamMember
actor "QA" as QA
actor "Developer" as Dev
actor "Project Manager" as PM

TeamMember <|-- QA
TeamMember <|-- Dev
TeamMember <|-- PM

rectangle "Bug Tracker" {
  usecase UC_ViewList as "View bug list"
  usecase UC_ViewDetails as "View bug details"
  usecase UC_AddComment as "Add comment"
  usecase UC_CreateBug as "Create bug report"
  usecase UC_ChangeStatus as "Change bug status"
  usecase UC_AssignBug as "Assign performer"
  usecase UC_LinkCommit as "Link commit"
  usecase UC_GenReport as "Generate report"
  usecase UC_AttachFile as "Attach file"
  usecase UC_FilterList as "Filter list"
  usecase UC_BatchEdit as "Batch edit bugs"
  usecase UC_LinkBugs as "Link bugs"
  usecase UC_GenPDF as "Generate PDF report"
  usecase UC_GenCSV as "Generate CSV report"

  TeamMember --> UC_ViewList
  TeamMember --> UC_ViewDetails
  TeamMember --> UC_AddComment
  TeamMember --> UC_AttachFile
  TeamMember --> UC_LinkBugs
  TeamMember --> UC_FilterList

  QA --> UC_CreateBug
  QA --> UC_ChangeStatus

  Dev --> UC_ChangeStatus
  Dev --> UC_AssignBug
  Dev --> UC_LinkCommit

  PM --> UC_GenReport
  PM --> UC_BatchEdit
  PM --> UC_AssignBug

  UC_GenReport <|-- UC_GenPDF
  UC_GenReport <|-- UC_GenCSV

  UC_ViewList <.. UC_FilterList : <<extends>>
  UC_ViewList <.. UC_BatchEdit : <<extends>>
  UC_ViewDetails <.. UC_LinkBugs : <<extends>>
  UC_ChangeStatus <.. UC_BatchEdit : <<extends>>
  UC_AssignBug <.. UC_BatchEdit : <<extends>>

  UC_CreateBug ..> UC_AttachFile : <<include>>
  UC_AddComment ..> UC_AttachFile : <<include>>
}
@enduml