@startuml
left to right direction

actor "Team Member" as TeamMember
actor "QA" as QA
actor "Developer" as Dev
actor "Project Manager" as PM
actor "Notification Service" as NotifService <<system>>
actor "Git Repository" as GitRepo <<system>>

TeamMember <|-- QA : extends
TeamMember <|-- Dev : extends
TeamMember <|-- PM : extends

rectangle "Bug Tracker" {
  usecase UC_ViewList as "View bug list"
  usecase UC_ViewDetails as "View bug details"
  usecase UC_AddComment as "Add comment"
  usecase UC_CreateBug as "Create bug report"
  usecase UC_ChangeStatus as "Change bug status"
  usecase UC_AssignBug as "Assign performer"
  usecase UC_LinkCommit as "Link commit"
  usecase UC_GenReport as "Generate report"
  usecase UC_Notify as "Send notification"
  usecase UC_AttachFile as "Attach file"
  usecase UC_FilterList as "Filter list"
  usecase UC_BatchEdit as "Batch edit bugs"
  usecase UC_LinkBugs as "Link bugs"
  usecase UC_VerifyFix as "Verify fix"
  usecase UC_CloseBug as "Close bug"
  usecase UC_ReopenBug as "Reopen bug"

  TeamMember --> UC_ViewList
  TeamMember --> UC_ViewDetails
  TeamMember --> UC_AddComment

  QA --> UC_CreateBug
  QA --> UC_VerifyFix

  Dev --> UC_ChangeStatus
  Dev --> UC_AssignBug
  Dev --> UC_LinkCommit

  PM --> UC_GenReport
  PM --> UC_BatchEdit

  UC_LinkCommit --> GitRepo
  UC_Notify --> NotifService

  UC_VerifyFix <|-- UC_CloseBug : extends
  UC_VerifyFix <|-- UC_ReopenBug : extends
  UC_CreateBug ..> UC_Notify : use
  UC_ChangeStatus ..> UC_Notify : use
  UC_AddComment ..> UC_Notify : use
  UC_AssignBug ..> UC_Notify : use
  UC_VerifyFix ..> UC_Notify : use
  UC_BatchEdit ..> UC_Notify : use
  UC_CreateBug ..> UC_AttachFile : use
  UC_AddComment ..> UC_AttachFile : use
  UC_ViewDetails <.. UC_LinkBugs : use
  UC_ViewList <.. UC_FilterList : use
  UC_ViewList <.. UC_BatchEdit : use
}
@enduml